// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: cost.sql

package sqlcgen

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const createRunCost = `-- name: CreateRunCost :one
INSERT INTO run_costs (run_id, source, duration_ms, amount_micros, currency)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (run_id) WHERE source = 'ci_duration' DO NOTHING
RETURNING id, run_id, source, duration_ms, amount_micros, currency, captured_at
`

type CreateRunCostParams struct {
	RunID        uuid.UUID     `json:"run_id"`
	Source       string        `json:"source"`
	DurationMs   sql.NullInt64 `json:"duration_ms"`
	AmountMicros sql.NullInt64 `json:"amount_micros"`
	Currency     string        `json:"currency"`
}

func (q *Queries) CreateRunCost(ctx context.Context, arg CreateRunCostParams) (RunCost, error) {
	row := q.db.QueryRowContext(ctx, createRunCost,
		arg.RunID,
		arg.Source,
		arg.DurationMs,
		arg.AmountMicros,
		arg.Currency,
	)
	var i RunCost
	err := row.Scan(
		&i.ID,
		&i.RunID,
		&i.Source,
		&i.DurationMs,
		&i.AmountMicros,
		&i.Currency,
		&i.CapturedAt,
	)
	return i, err
}

const findCostRate = `-- name: FindCostRate :one
SELECT id, tenant_id, environment_id, ci_provider, rate_micros_per_ms, currency, created_at FROM cost_rates
WHERE tenant_id = $1
  AND (environment_id = $2 OR environment_id IS NULL)
  AND (ci_provider = $3 OR ci_provider IS NULL)
ORDER BY (environment_id IS NOT NULL) DESC, (ci_provider IS NOT NULL) DESC
LIMIT 1
`

type FindCostRateParams struct {
	TenantID      uuid.UUID      `json:"tenant_id"`
	EnvironmentID uuid.NullUUID  `json:"environment_id"`
	CiProvider    sql.NullString `json:"ci_provider"`
}

func (q *Queries) FindCostRate(ctx context.Context, arg FindCostRateParams) (CostRate, error) {
	row := q.db.QueryRowContext(ctx, findCostRate, arg.TenantID, arg.EnvironmentID, arg.CiProvider)
	var i CostRate
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.EnvironmentID,
		&i.CiProvider,
		&i.RateMicrosPerMs,
		&i.Currency,
		&i.CreatedAt,
	)
	return i, err
}

const getCostsForRun = `-- name: GetCostsForRun :many
SELECT id, run_id, source, duration_ms, amount_micros, currency, captured_at FROM run_costs WHERE run_id = $1 ORDER BY captured_at
`

func (q *Queries) GetCostsForRun(ctx context.Context, runID uuid.UUID) ([]RunCost, error) {
	rows, err := q.db.QueryContext(ctx, getCostsForRun, runID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RunCost
	for rows.Next() {
		var i RunCost
		if err := rows.Scan(
			&i.ID,
			&i.RunID,
			&i.Source,
			&i.DurationMs,
			&i.AmountMicros,
			&i.Currency,
			&i.CapturedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRunCostByRunAndSource = `-- name: GetRunCostByRunAndSource :one
SELECT id, run_id, source, duration_ms, amount_micros, currency, captured_at FROM run_costs WHERE run_id = $1 AND source = $2
`

type GetRunCostByRunAndSourceParams struct {
	RunID  uuid.UUID `json:"run_id"`
	Source string    `json:"source"`
}

func (q *Queries) GetRunCostByRunAndSource(ctx context.Context, arg GetRunCostByRunAndSourceParams) (RunCost, error) {
	row := q.db.QueryRowContext(ctx, getRunCostByRunAndSource, arg.RunID, arg.Source)
	var i RunCost
	err := row.Scan(
		&i.ID,
		&i.RunID,
		&i.Source,
		&i.DurationMs,
		&i.AmountMicros,
		&i.Currency,
		&i.CapturedAt,
	)
	return i, err
}

const sumCostByActor = `-- name: SumCostByActor :many
SELECT runs.actor_id,
       COALESCE(SUM(run_costs.amount_micros), 0)::bigint AS total_amount_micros,
       BOOL_OR(run_costs.amount_micros IS NOT NULL)::bool AS has_amount,
       COALESCE(SUM(run_costs.duration_ms), 0)::bigint AS total_duration_ms,
       COUNT(*)::bigint AS run_count
FROM run_costs
JOIN runs ON runs.id = run_costs.run_id
WHERE runs.tenant_id = $1
  AND ($2::uuid IS NULL OR runs.actor_id = $2)
  AND ($3::timestamptz IS NULL OR run_costs.captured_at >= $3)
  AND ($4::timestamptz IS NULL OR run_costs.captured_at < $4)
GROUP BY runs.actor_id
ORDER BY total_amount_micros DESC NULLS LAST
`

type SumCostByActorParams struct {
	TenantID     uuid.UUID     `json:"tenant_id"`
	ActorID      uuid.NullUUID `json:"actor_id"`
	CapturedFrom sql.NullTime  `json:"captured_from"`
	CapturedTo   sql.NullTime  `json:"captured_to"`
}

type SumCostByActorRow struct {
	ActorID           uuid.UUID `json:"actor_id"`
	TotalAmountMicros int64     `json:"total_amount_micros"`
	HasAmount         bool      `json:"has_amount"`
	TotalDurationMs   int64     `json:"total_duration_ms"`
	RunCount          int64     `json:"run_count"`
}

func (q *Queries) SumCostByActor(ctx context.Context, arg SumCostByActorParams) ([]SumCostByActorRow, error) {
	rows, err := q.db.QueryContext(ctx, sumCostByActor,
		arg.TenantID,
		arg.ActorID,
		arg.CapturedFrom,
		arg.CapturedTo,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SumCostByActorRow
	for rows.Next() {
		var i SumCostByActorRow
		if err := rows.Scan(
			&i.ActorID,
			&i.TotalAmountMicros,
			&i.HasAmount,
			&i.TotalDurationMs,
			&i.RunCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertCostRate = `-- name: UpsertCostRate :one
INSERT INTO cost_rates (tenant_id, environment_id, ci_provider, rate_micros_per_ms, currency)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (tenant_id, COALESCE(environment_id, '00000000-0000-0000-0000-000000000000'), COALESCE(ci_provider, ''))
DO UPDATE SET rate_micros_per_ms = EXCLUDED.rate_micros_per_ms, currency = EXCLUDED.currency
RETURNING id, tenant_id, environment_id, ci_provider, rate_micros_per_ms, currency, created_at
`

type UpsertCostRateParams struct {
	TenantID        uuid.UUID      `json:"tenant_id"`
	EnvironmentID   uuid.NullUUID  `json:"environment_id"`
	CiProvider      sql.NullString `json:"ci_provider"`
	RateMicrosPerMs int64          `json:"rate_micros_per_ms"`
	Currency        string         `json:"currency"`
}

func (q *Queries) UpsertCostRate(ctx context.Context, arg UpsertCostRateParams) (CostRate, error) {
	row := q.db.QueryRowContext(ctx, upsertCostRate,
		arg.TenantID,
		arg.EnvironmentID,
		arg.CiProvider,
		arg.RateMicrosPerMs,
		arg.Currency,
	)
	var i CostRate
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.EnvironmentID,
		&i.CiProvider,
		&i.RateMicrosPerMs,
		&i.Currency,
		&i.CreatedAt,
	)
	return i, err
}
