// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CreateRunCost(ctx context.Context, arg CreateRunCostParams) (RunCost, error)
	FindCostRate(ctx context.Context, arg FindCostRateParams) (CostRate, error)
	GetCostsForRun(ctx context.Context, runID uuid.UUID) ([]RunCost, error)
	GetRunCostByRunAndSource(ctx context.Context, arg GetRunCostByRunAndSourceParams) (RunCost, error)
	SumCostByActor(ctx context.Context, arg SumCostByActorParams) ([]SumCostByActorRow, error)
	UpsertCostRate(ctx context.Context, arg UpsertCostRateParams) (CostRate, error)
}

var _ Querier = (*Queries)(nil)
