// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: credential.sql

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
)

const createLocalUser = `-- name: CreateLocalUser :one
INSERT INTO local_users (actor_id, username, password_hash) VALUES ($1, $2, $3) RETURNING actor_id, username, password_hash, created_at
`

type CreateLocalUserParams struct {
	ActorID      uuid.UUID `json:"actor_id"`
	Username     string    `json:"username"`
	PasswordHash string    `json:"password_hash"`
}

func (q *Queries) CreateLocalUser(ctx context.Context, arg CreateLocalUserParams) (LocalUser, error) {
	row := q.db.QueryRowContext(ctx, createLocalUser, arg.ActorID, arg.Username, arg.PasswordHash)
	var i LocalUser
	err := row.Scan(
		&i.ActorID,
		&i.Username,
		&i.PasswordHash,
		&i.CreatedAt,
	)
	return i, err
}

const getLocalUserByUsername = `-- name: GetLocalUserByUsername :one
SELECT actor_id, username, password_hash, created_at FROM local_users WHERE username = $1
`

func (q *Queries) GetLocalUserByUsername(ctx context.Context, username string) (LocalUser, error) {
	row := q.db.QueryRowContext(ctx, getLocalUserByUsername, username)
	var i LocalUser
	err := row.Scan(
		&i.ActorID,
		&i.Username,
		&i.PasswordHash,
		&i.CreatedAt,
	)
	return i, err
}
