// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcgen

import (
	"context"
)

type Querier interface {
	CreateLocalUser(ctx context.Context, arg CreateLocalUserParams) (LocalUser, error)
	GetLocalUserByUsername(ctx context.Context, username string) (LocalUser, error)
}

var _ Querier = (*Queries)(nil)
