// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcgen

import (
	"context"
	"time"
)

type Querier interface {
	CountActiveAgents(ctx context.Context) (int64, error)
	CountRunsSince(ctx context.Context, requestedAt time.Time) (int64, error)
	CreateTelemetryInstance(ctx context.Context) (TelemetryInstance, error)
	GetTelemetryInstance(ctx context.Context) (TelemetryInstance, error)
}

var _ Querier = (*Queries)(nil)
