// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: telemetry.sql

package sqlcgen

import (
	"context"
	"time"
)

const countActiveAgents = `-- name: CountActiveAgents :one
SELECT COUNT(*)::bigint FROM actors WHERE type = 'agent' AND status = 'active'
`

func (q *Queries) CountActiveAgents(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countActiveAgents)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const countRunsSince = `-- name: CountRunsSince :one
SELECT COUNT(*)::bigint FROM runs WHERE requested_at >= $1
`

func (q *Queries) CountRunsSince(ctx context.Context, requestedAt time.Time) (int64, error) {
	row := q.db.QueryRowContext(ctx, countRunsSince, requestedAt)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const createTelemetryInstance = `-- name: CreateTelemetryInstance :one
INSERT INTO telemetry_instance DEFAULT VALUES RETURNING id, singleton, created_at
`

func (q *Queries) CreateTelemetryInstance(ctx context.Context) (TelemetryInstance, error) {
	row := q.db.QueryRowContext(ctx, createTelemetryInstance)
	var i TelemetryInstance
	err := row.Scan(&i.ID, &i.Singleton, &i.CreatedAt)
	return i, err
}

const getTelemetryInstance = `-- name: GetTelemetryInstance :one
SELECT id, singleton, created_at FROM telemetry_instance LIMIT 1
`

func (q *Queries) GetTelemetryInstance(ctx context.Context) (TelemetryInstance, error) {
	row := q.db.QueryRowContext(ctx, getTelemetryInstance)
	var i TelemetryInstance
	err := row.Scan(&i.ID, &i.Singleton, &i.CreatedAt)
	return i, err
}
