// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: actor.sql

package sqlcgen

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const createActor = `-- name: CreateActor :one
INSERT INTO actors (tenant_id, type, name, team_id, trust_tier, authorized_by, expires_at)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, tenant_id, type, name, team_id, trust_tier, authorized_by, status, expires_at, created_at, revoked_at
`

type CreateActorParams struct {
	TenantID     uuid.UUID     `json:"tenant_id"`
	Type         string        `json:"type"`
	Name         string        `json:"name"`
	TeamID       uuid.UUID     `json:"team_id"`
	TrustTier    int16         `json:"trust_tier"`
	AuthorizedBy uuid.NullUUID `json:"authorized_by"`
	ExpiresAt    sql.NullTime  `json:"expires_at"`
}

func (q *Queries) CreateActor(ctx context.Context, arg CreateActorParams) (Actor, error) {
	row := q.db.QueryRowContext(ctx, createActor,
		arg.TenantID,
		arg.Type,
		arg.Name,
		arg.TeamID,
		arg.TrustTier,
		arg.AuthorizedBy,
		arg.ExpiresAt,
	)
	var i Actor
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Type,
		&i.Name,
		&i.TeamID,
		&i.TrustTier,
		&i.AuthorizedBy,
		&i.Status,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.RevokedAt,
	)
	return i, err
}

const getActor = `-- name: GetActor :one
SELECT id, tenant_id, type, name, team_id, trust_tier, authorized_by, status, expires_at, created_at, revoked_at FROM actors WHERE id = $1
`

func (q *Queries) GetActor(ctx context.Context, id uuid.UUID) (Actor, error) {
	row := q.db.QueryRowContext(ctx, getActor, id)
	var i Actor
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Type,
		&i.Name,
		&i.TeamID,
		&i.TrustTier,
		&i.AuthorizedBy,
		&i.Status,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.RevokedAt,
	)
	return i, err
}
