// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CreateActor(ctx context.Context, arg CreateActorParams) (Actor, error)
	GetActor(ctx context.Context, id uuid.UUID) (Actor, error)
}

var _ Querier = (*Queries)(nil)
