// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CreateActor(ctx context.Context, arg CreateActorParams) (Actor, error)
	GetActor(ctx context.Context, id uuid.UUID) (Actor, error)
	GetActorByIdempotencyKey(ctx context.Context, arg GetActorByIdempotencyKeyParams) (Actor, error)
	GetRootActor(ctx context.Context, tenantID uuid.UUID) (Actor, error)
	GrantActorEnvironment(ctx context.Context, arg GrantActorEnvironmentParams) error
	ListActorEnvironments(ctx context.Context, actorID uuid.UUID) ([]uuid.UUID, error)
}

var _ Querier = (*Queries)(nil)
