// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcgen

import (
	"context"
	"database/sql"
)

type Querier interface {
	DeleteExpiredSessions(ctx context.Context) (int64, error)
	IsRevoked(ctx context.Context, arg IsRevokedParams) (sql.NullBool, error)
	RevokeSession(ctx context.Context, arg RevokeSessionParams) (RevokedSession, error)
}

var _ Querier = (*Queries)(nil)
