// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: session.sql

package sqlcgen

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const deleteExpiredSessions = `-- name: DeleteExpiredSessions :execrows
DELETE FROM revoked_sessions WHERE expires_at < now()
`

func (q *Queries) DeleteExpiredSessions(ctx context.Context) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteExpiredSessions)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const isRevoked = `-- name: IsRevoked :one
SELECT
    EXISTS (SELECT 1 FROM actors WHERE id = $1 AND status = 'revoked')
    OR EXISTS (SELECT 1 FROM revoked_sessions WHERE jti = $2)
    AS is_revoked
`

type IsRevokedParams struct {
	ID  uuid.UUID `json:"id"`
	Jti uuid.UUID `json:"jti"`
}

func (q *Queries) IsRevoked(ctx context.Context, arg IsRevokedParams) (sql.NullBool, error) {
	row := q.db.QueryRowContext(ctx, isRevoked, arg.ID, arg.Jti)
	var is_revoked sql.NullBool
	err := row.Scan(&is_revoked)
	return is_revoked, err
}

const revokeSession = `-- name: RevokeSession :one
INSERT INTO revoked_sessions (jti, actor_id, expires_at) VALUES ($1, $2, $3) RETURNING jti, actor_id, revoked_at, expires_at
`

type RevokeSessionParams struct {
	Jti       uuid.UUID `json:"jti"`
	ActorID   uuid.UUID `json:"actor_id"`
	ExpiresAt time.Time `json:"expires_at"`
}

func (q *Queries) RevokeSession(ctx context.Context, arg RevokeSessionParams) (RevokedSession, error) {
	row := q.db.QueryRowContext(ctx, revokeSession, arg.Jti, arg.ActorID, arg.ExpiresAt)
	var i RevokedSession
	err := row.Scan(
		&i.Jti,
		&i.ActorID,
		&i.RevokedAt,
		&i.ExpiresAt,
	)
	return i, err
}
