// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CreateWorkerCredential(ctx context.Context, arg CreateWorkerCredentialParams) (WorkerCredential, error)
	GetWorkerCredential(ctx context.Context, id uuid.UUID) (WorkerCredential, error)
	GetWorkerCredentialByTokenHash(ctx context.Context, tokenHash string) (WorkerCredential, error)
	GrantWorkerCredentialEnvironment(ctx context.Context, arg GrantWorkerCredentialEnvironmentParams) error
	ListWorkerCredentialEnvironments(ctx context.Context, workerCredentialID uuid.UUID) ([]uuid.UUID, error)
}

var _ Querier = (*Queries)(nil)
