// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: workercred.sql

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
)

const createWorkerCredential = `-- name: CreateWorkerCredential :one
INSERT INTO worker_credentials (tenant_id, name, token_hash) VALUES ($1, $2, $3) RETURNING id, tenant_id, name, token_hash, created_at, revoked_at
`

type CreateWorkerCredentialParams struct {
	TenantID  uuid.UUID `json:"tenant_id"`
	Name      string    `json:"name"`
	TokenHash string    `json:"token_hash"`
}

func (q *Queries) CreateWorkerCredential(ctx context.Context, arg CreateWorkerCredentialParams) (WorkerCredential, error) {
	row := q.db.QueryRowContext(ctx, createWorkerCredential, arg.TenantID, arg.Name, arg.TokenHash)
	var i WorkerCredential
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.TokenHash,
		&i.CreatedAt,
		&i.RevokedAt,
	)
	return i, err
}

const getWorkerCredential = `-- name: GetWorkerCredential :one
SELECT id, tenant_id, name, token_hash, created_at, revoked_at FROM worker_credentials WHERE id = $1
`

func (q *Queries) GetWorkerCredential(ctx context.Context, id uuid.UUID) (WorkerCredential, error) {
	row := q.db.QueryRowContext(ctx, getWorkerCredential, id)
	var i WorkerCredential
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.TokenHash,
		&i.CreatedAt,
		&i.RevokedAt,
	)
	return i, err
}

const getWorkerCredentialByTenantAndName = `-- name: GetWorkerCredentialByTenantAndName :one
SELECT id, tenant_id, name, token_hash, created_at, revoked_at FROM worker_credentials WHERE tenant_id = $1 AND name = $2 AND revoked_at IS NULL
`

type GetWorkerCredentialByTenantAndNameParams struct {
	TenantID uuid.UUID `json:"tenant_id"`
	Name     string    `json:"name"`
}

func (q *Queries) GetWorkerCredentialByTenantAndName(ctx context.Context, arg GetWorkerCredentialByTenantAndNameParams) (WorkerCredential, error) {
	row := q.db.QueryRowContext(ctx, getWorkerCredentialByTenantAndName, arg.TenantID, arg.Name)
	var i WorkerCredential
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.TokenHash,
		&i.CreatedAt,
		&i.RevokedAt,
	)
	return i, err
}

const getWorkerCredentialByTokenHash = `-- name: GetWorkerCredentialByTokenHash :one
SELECT id, tenant_id, name, token_hash, created_at, revoked_at FROM worker_credentials WHERE token_hash = $1 AND revoked_at IS NULL
`

func (q *Queries) GetWorkerCredentialByTokenHash(ctx context.Context, tokenHash string) (WorkerCredential, error) {
	row := q.db.QueryRowContext(ctx, getWorkerCredentialByTokenHash, tokenHash)
	var i WorkerCredential
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.TokenHash,
		&i.CreatedAt,
		&i.RevokedAt,
	)
	return i, err
}

const grantWorkerCredentialEnvironment = `-- name: GrantWorkerCredentialEnvironment :exec
INSERT INTO worker_credential_environments (worker_credential_id, environment_id)
VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

type GrantWorkerCredentialEnvironmentParams struct {
	WorkerCredentialID uuid.UUID `json:"worker_credential_id"`
	EnvironmentID      uuid.UUID `json:"environment_id"`
}

func (q *Queries) GrantWorkerCredentialEnvironment(ctx context.Context, arg GrantWorkerCredentialEnvironmentParams) error {
	_, err := q.db.ExecContext(ctx, grantWorkerCredentialEnvironment, arg.WorkerCredentialID, arg.EnvironmentID)
	return err
}

const listWorkerCredentialEnvironments = `-- name: ListWorkerCredentialEnvironments :many
SELECT environment_id FROM worker_credential_environments WHERE worker_credential_id = $1
`

func (q *Queries) ListWorkerCredentialEnvironments(ctx context.Context, workerCredentialID uuid.UUID) ([]uuid.UUID, error) {
	rows, err := q.db.QueryContext(ctx, listWorkerCredentialEnvironments, workerCredentialID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []uuid.UUID
	for rows.Next() {
		var environment_id uuid.UUID
		if err := rows.Scan(&environment_id); err != nil {
			return nil, err
		}
		items = append(items, environment_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWorkerCredentials = `-- name: ListWorkerCredentials :many
SELECT id, tenant_id, name, token_hash, created_at, revoked_at FROM worker_credentials WHERE tenant_id = $1 ORDER BY name
`

func (q *Queries) ListWorkerCredentials(ctx context.Context, tenantID uuid.UUID) ([]WorkerCredential, error) {
	rows, err := q.db.QueryContext(ctx, listWorkerCredentials, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []WorkerCredential
	for rows.Next() {
		var i WorkerCredential
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Name,
			&i.TokenHash,
			&i.CreatedAt,
			&i.RevokedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const rotateWorkerCredentialToken = `-- name: RotateWorkerCredentialToken :one
UPDATE worker_credentials SET token_hash = $2 WHERE id = $1 RETURNING id, tenant_id, name, token_hash, created_at, revoked_at
`

type RotateWorkerCredentialTokenParams struct {
	ID        uuid.UUID `json:"id"`
	TokenHash string    `json:"token_hash"`
}

func (q *Queries) RotateWorkerCredentialToken(ctx context.Context, arg RotateWorkerCredentialTokenParams) (WorkerCredential, error) {
	row := q.db.QueryRowContext(ctx, rotateWorkerCredentialToken, arg.ID, arg.TokenHash)
	var i WorkerCredential
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.TokenHash,
		&i.CreatedAt,
		&i.RevokedAt,
	)
	return i, err
}
