// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: execution.sql

package sqlcgen

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const createApproval = `-- name: CreateApproval :one
INSERT INTO approvals (run_id) VALUES ($1) RETURNING id, run_id, requested_at, approver_actor_id, decision, decided_at
`

func (q *Queries) CreateApproval(ctx context.Context, runID uuid.UUID) (Approval, error) {
	row := q.db.QueryRowContext(ctx, createApproval, runID)
	var i Approval
	err := row.Scan(
		&i.ID,
		&i.RunID,
		&i.RequestedAt,
		&i.ApproverActorID,
		&i.Decision,
		&i.DecidedAt,
	)
	return i, err
}

const createRun = `-- name: CreateRun :one
INSERT INTO runs (
    tenant_id, actor_id, environment_id, pipeline_id, tier, status,
    ci_provider, idempotency_key, diff_ref
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9
)
RETURNING id, tenant_id, actor_id, environment_id, binding_id, pipeline_id, tier, status, ci_provider, ci_external_ref, ci_raw_status, ci_url, idempotency_key, diff_ref, requested_at, started_at, finished_at, created_at
`

type CreateRunParams struct {
	TenantID       uuid.UUID      `json:"tenant_id"`
	ActorID        uuid.UUID      `json:"actor_id"`
	EnvironmentID  uuid.UUID      `json:"environment_id"`
	PipelineID     uuid.UUID      `json:"pipeline_id"`
	Tier           int16          `json:"tier"`
	Status         string         `json:"status"`
	CiProvider     string         `json:"ci_provider"`
	IdempotencyKey sql.NullString `json:"idempotency_key"`
	DiffRef        sql.NullString `json:"diff_ref"`
}

func (q *Queries) CreateRun(ctx context.Context, arg CreateRunParams) (Run, error) {
	row := q.db.QueryRowContext(ctx, createRun,
		arg.TenantID,
		arg.ActorID,
		arg.EnvironmentID,
		arg.PipelineID,
		arg.Tier,
		arg.Status,
		arg.CiProvider,
		arg.IdempotencyKey,
		arg.DiffRef,
	)
	var i Run
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ActorID,
		&i.EnvironmentID,
		&i.BindingID,
		&i.PipelineID,
		&i.Tier,
		&i.Status,
		&i.CiProvider,
		&i.CiExternalRef,
		&i.CiRawStatus,
		&i.CiUrl,
		&i.IdempotencyKey,
		&i.DiffRef,
		&i.RequestedAt,
		&i.StartedAt,
		&i.FinishedAt,
		&i.CreatedAt,
	)
	return i, err
}

const decideApproval = `-- name: DecideApproval :one
UPDATE approvals
SET decision = $1, decided_at = now(), approver_actor_id = $2
WHERE run_id = $3 AND decision IS NULL
RETURNING id, run_id, requested_at, approver_actor_id, decision, decided_at
`

type DecideApprovalParams struct {
	Decision        sql.NullString `json:"decision"`
	ApproverActorID uuid.NullUUID  `json:"approver_actor_id"`
	RunID           uuid.UUID      `json:"run_id"`
}

func (q *Queries) DecideApproval(ctx context.Context, arg DecideApprovalParams) (Approval, error) {
	row := q.db.QueryRowContext(ctx, decideApproval, arg.Decision, arg.ApproverActorID, arg.RunID)
	var i Approval
	err := row.Scan(
		&i.ID,
		&i.RunID,
		&i.RequestedAt,
		&i.ApproverActorID,
		&i.Decision,
		&i.DecidedAt,
	)
	return i, err
}

const getApprovalByRunID = `-- name: GetApprovalByRunID :one
SELECT id, run_id, requested_at, approver_actor_id, decision, decided_at FROM approvals WHERE run_id = $1
`

func (q *Queries) GetApprovalByRunID(ctx context.Context, runID uuid.UUID) (Approval, error) {
	row := q.db.QueryRowContext(ctx, getApprovalByRunID, runID)
	var i Approval
	err := row.Scan(
		&i.ID,
		&i.RunID,
		&i.RequestedAt,
		&i.ApproverActorID,
		&i.Decision,
		&i.DecidedAt,
	)
	return i, err
}

const getRun = `-- name: GetRun :one
SELECT id, tenant_id, actor_id, environment_id, binding_id, pipeline_id, tier, status, ci_provider, ci_external_ref, ci_raw_status, ci_url, idempotency_key, diff_ref, requested_at, started_at, finished_at, created_at FROM runs WHERE tenant_id = $1 AND id = $2
`

type GetRunParams struct {
	TenantID uuid.UUID `json:"tenant_id"`
	ID       uuid.UUID `json:"id"`
}

func (q *Queries) GetRun(ctx context.Context, arg GetRunParams) (Run, error) {
	row := q.db.QueryRowContext(ctx, getRun, arg.TenantID, arg.ID)
	var i Run
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ActorID,
		&i.EnvironmentID,
		&i.BindingID,
		&i.PipelineID,
		&i.Tier,
		&i.Status,
		&i.CiProvider,
		&i.CiExternalRef,
		&i.CiRawStatus,
		&i.CiUrl,
		&i.IdempotencyKey,
		&i.DiffRef,
		&i.RequestedAt,
		&i.StartedAt,
		&i.FinishedAt,
		&i.CreatedAt,
	)
	return i, err
}

const updateRunStatus = `-- name: UpdateRunStatus :one
UPDATE runs
SET status = $1::text,
    started_at = CASE WHEN $1::text = 'executing' AND started_at IS NULL THEN now() ELSE started_at END,
    finished_at = CASE WHEN $1::text IN ('succeeded', 'failed', 'cancelled', 'timed_out') THEN now() ELSE finished_at END
WHERE id = $2 AND status = $3
RETURNING id, tenant_id, actor_id, environment_id, binding_id, pipeline_id, tier, status, ci_provider, ci_external_ref, ci_raw_status, ci_url, idempotency_key, diff_ref, requested_at, started_at, finished_at, created_at
`

type UpdateRunStatusParams struct {
	NewStatus string    `json:"new_status"`
	ID        uuid.UUID `json:"id"`
	OldStatus string    `json:"old_status"`
}

func (q *Queries) UpdateRunStatus(ctx context.Context, arg UpdateRunStatusParams) (Run, error) {
	row := q.db.QueryRowContext(ctx, updateRunStatus, arg.NewStatus, arg.ID, arg.OldStatus)
	var i Run
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ActorID,
		&i.EnvironmentID,
		&i.BindingID,
		&i.PipelineID,
		&i.Tier,
		&i.Status,
		&i.CiProvider,
		&i.CiExternalRef,
		&i.CiRawStatus,
		&i.CiUrl,
		&i.IdempotencyKey,
		&i.DiffRef,
		&i.RequestedAt,
		&i.StartedAt,
		&i.FinishedAt,
		&i.CreatedAt,
	)
	return i, err
}
