// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CreateApproval(ctx context.Context, runID uuid.UUID) (Approval, error)
	CreateRun(ctx context.Context, arg CreateRunParams) (Run, error)
	DecideApproval(ctx context.Context, arg DecideApprovalParams) (Approval, error)
	GetApprovalByRunID(ctx context.Context, runID uuid.UUID) (Approval, error)
	GetRun(ctx context.Context, arg GetRunParams) (Run, error)
	UpdateRunStatus(ctx context.Context, arg UpdateRunStatusParams) (Run, error)
}

var _ Querier = (*Queries)(nil)
