// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcgen

import (
	"context"
)

type Querier interface {
	CreateSigningKey(ctx context.Context, privateKey []byte) (SigningKey, error)
	GetSigningKey(ctx context.Context) (SigningKey, error)
}

var _ Querier = (*Queries)(nil)
