// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: signingkey.sql

package sqlcgen

import (
	"context"
)

const createSigningKey = `-- name: CreateSigningKey :one
INSERT INTO signing_keys (private_key) VALUES ($1) RETURNING id, private_key, created_at
`

func (q *Queries) CreateSigningKey(ctx context.Context, privateKey []byte) (SigningKey, error) {
	row := q.db.QueryRowContext(ctx, createSigningKey, privateKey)
	var i SigningKey
	err := row.Scan(&i.ID, &i.PrivateKey, &i.CreatedAt)
	return i, err
}

const getSigningKey = `-- name: GetSigningKey :one
SELECT id, private_key, created_at FROM signing_keys WHERE id = true
`

func (q *Queries) GetSigningKey(ctx context.Context) (SigningKey, error) {
	row := q.db.QueryRowContext(ctx, getSigningKey)
	var i SigningKey
	err := row.Scan(&i.ID, &i.PrivateKey, &i.CreatedAt)
	return i, err
}
