// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	ClaimNextPendingVerification(ctx context.Context, arg ClaimNextPendingVerificationParams) (EnvironmentVerification, error)
	CompleteVerification(ctx context.Context, arg CompleteVerificationParams) (EnvironmentVerification, error)
	CreateVerification(ctx context.Context, arg CreateVerificationParams) (EnvironmentVerification, error)
	GetVerification(ctx context.Context, id uuid.UUID) (EnvironmentVerification, error)
}

var _ Querier = (*Queries)(nil)
