// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: verification.sql

package sqlcgen

import (
	"context"
	"encoding/json"

	"github.com/google/uuid"
	"github.com/lib/pq"
)

const claimNextPendingVerification = `-- name: ClaimNextPendingVerification :one
WITH next AS (
    SELECT id FROM environment_verifications
    WHERE status = 'pending' AND claimed_by IS NULL AND environment_id = ANY($2::uuid[])
    ORDER BY requested_at
    FOR UPDATE SKIP LOCKED
    LIMIT 1
)
UPDATE environment_verifications
SET claimed_by = $1, claimed_at = now()
WHERE id = (SELECT id FROM next)
RETURNING id, tenant_id, environment_id, status, requested_by, claimed_by, tier_results, requested_at, claimed_at, completed_at
`

type ClaimNextPendingVerificationParams struct {
	ClaimedBy      uuid.NullUUID `json:"claimed_by"`
	EnvironmentIds []uuid.UUID   `json:"environment_ids"`
}

func (q *Queries) ClaimNextPendingVerification(ctx context.Context, arg ClaimNextPendingVerificationParams) (EnvironmentVerification, error) {
	row := q.db.QueryRowContext(ctx, claimNextPendingVerification, arg.ClaimedBy, pq.Array(arg.EnvironmentIds))
	var i EnvironmentVerification
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.EnvironmentID,
		&i.Status,
		&i.RequestedBy,
		&i.ClaimedBy,
		&i.TierResults,
		&i.RequestedAt,
		&i.ClaimedAt,
		&i.CompletedAt,
	)
	return i, err
}

const completeVerification = `-- name: CompleteVerification :one
UPDATE environment_verifications
SET status = $2, tier_results = $3, completed_at = now()
WHERE id = $1 AND claimed_by = $4
RETURNING id, tenant_id, environment_id, status, requested_by, claimed_by, tier_results, requested_at, claimed_at, completed_at
`

type CompleteVerificationParams struct {
	ID          uuid.UUID       `json:"id"`
	Status      string          `json:"status"`
	TierResults json.RawMessage `json:"tier_results"`
	ClaimedBy   uuid.NullUUID   `json:"claimed_by"`
}

func (q *Queries) CompleteVerification(ctx context.Context, arg CompleteVerificationParams) (EnvironmentVerification, error) {
	row := q.db.QueryRowContext(ctx, completeVerification,
		arg.ID,
		arg.Status,
		arg.TierResults,
		arg.ClaimedBy,
	)
	var i EnvironmentVerification
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.EnvironmentID,
		&i.Status,
		&i.RequestedBy,
		&i.ClaimedBy,
		&i.TierResults,
		&i.RequestedAt,
		&i.ClaimedAt,
		&i.CompletedAt,
	)
	return i, err
}

const createVerification = `-- name: CreateVerification :one
INSERT INTO environment_verifications (tenant_id, environment_id, requested_by)
VALUES ($1, $2, $3) RETURNING id, tenant_id, environment_id, status, requested_by, claimed_by, tier_results, requested_at, claimed_at, completed_at
`

type CreateVerificationParams struct {
	TenantID      uuid.UUID `json:"tenant_id"`
	EnvironmentID uuid.UUID `json:"environment_id"`
	RequestedBy   uuid.UUID `json:"requested_by"`
}

func (q *Queries) CreateVerification(ctx context.Context, arg CreateVerificationParams) (EnvironmentVerification, error) {
	row := q.db.QueryRowContext(ctx, createVerification, arg.TenantID, arg.EnvironmentID, arg.RequestedBy)
	var i EnvironmentVerification
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.EnvironmentID,
		&i.Status,
		&i.RequestedBy,
		&i.ClaimedBy,
		&i.TierResults,
		&i.RequestedAt,
		&i.ClaimedAt,
		&i.CompletedAt,
	)
	return i, err
}

const getVerification = `-- name: GetVerification :one
SELECT id, tenant_id, environment_id, status, requested_by, claimed_by, tier_results, requested_at, claimed_at, completed_at FROM environment_verifications WHERE id = $1
`

func (q *Queries) GetVerification(ctx context.Context, id uuid.UUID) (EnvironmentVerification, error) {
	row := q.db.QueryRowContext(ctx, getVerification, id)
	var i EnvironmentVerification
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.EnvironmentID,
		&i.Status,
		&i.RequestedBy,
		&i.ClaimedBy,
		&i.TierResults,
		&i.RequestedAt,
		&i.ClaimedAt,
		&i.CompletedAt,
	)
	return i, err
}
