// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: pipeline.sql

package sqlcgen

import (
	"context"
	"encoding/json"

	"github.com/google/uuid"
)

const createPipeline = `-- name: CreatePipeline :one
INSERT INTO pipelines (tenant_id, environment_id, provider, workflow_ref, settings, mutating)
VALUES ($1, $2, $3, $4, $5, $6) RETURNING id, tenant_id, environment_id, provider, workflow_ref, settings, mutating, created_at
`

type CreatePipelineParams struct {
	TenantID      uuid.UUID       `json:"tenant_id"`
	EnvironmentID uuid.UUID       `json:"environment_id"`
	Provider      string          `json:"provider"`
	WorkflowRef   string          `json:"workflow_ref"`
	Settings      json.RawMessage `json:"settings"`
	Mutating      bool            `json:"mutating"`
}

func (q *Queries) CreatePipeline(ctx context.Context, arg CreatePipelineParams) (Pipeline, error) {
	row := q.db.QueryRowContext(ctx, createPipeline,
		arg.TenantID,
		arg.EnvironmentID,
		arg.Provider,
		arg.WorkflowRef,
		arg.Settings,
		arg.Mutating,
	)
	var i Pipeline
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.EnvironmentID,
		&i.Provider,
		&i.WorkflowRef,
		&i.Settings,
		&i.Mutating,
		&i.CreatedAt,
	)
	return i, err
}

const getPipeline = `-- name: GetPipeline :one
SELECT id, tenant_id, environment_id, provider, workflow_ref, settings, mutating, created_at FROM pipelines WHERE id = $1 AND tenant_id = $2
`

type GetPipelineParams struct {
	ID       uuid.UUID `json:"id"`
	TenantID uuid.UUID `json:"tenant_id"`
}

func (q *Queries) GetPipeline(ctx context.Context, arg GetPipelineParams) (Pipeline, error) {
	row := q.db.QueryRowContext(ctx, getPipeline, arg.ID, arg.TenantID)
	var i Pipeline
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.EnvironmentID,
		&i.Provider,
		&i.WorkflowRef,
		&i.Settings,
		&i.Mutating,
		&i.CreatedAt,
	)
	return i, err
}
