// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcgen

import (
	"context"
)

type Querier interface {
	CreatePipeline(ctx context.Context, arg CreatePipelineParams) (Pipeline, error)
	GetPipeline(ctx context.Context, arg GetPipelineParams) (Pipeline, error)
}

var _ Querier = (*Queries)(nil)
