// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: environment.sql

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
)

const createEnvironment = `-- name: CreateEnvironment :one
INSERT INTO environments (tenant_id, name, provider, region) VALUES ($1, $2, $3, $4) RETURNING id, tenant_id, name, provider, region, created_at
`

type CreateEnvironmentParams struct {
	TenantID uuid.UUID `json:"tenant_id"`
	Name     string    `json:"name"`
	Provider string    `json:"provider"`
	Region   string    `json:"region"`
}

func (q *Queries) CreateEnvironment(ctx context.Context, arg CreateEnvironmentParams) (Environment, error) {
	row := q.db.QueryRowContext(ctx, createEnvironment,
		arg.TenantID,
		arg.Name,
		arg.Provider,
		arg.Region,
	)
	var i Environment
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.Provider,
		&i.Region,
		&i.CreatedAt,
	)
	return i, err
}

const createEnvironmentAWSConfig = `-- name: CreateEnvironmentAWSConfig :one
INSERT INTO environment_aws_config (environment_id, account_ref, external_id, trust_anchor)
VALUES ($1, $2, $3, $4) RETURNING environment_id, account_ref, external_id, trust_anchor
`

type CreateEnvironmentAWSConfigParams struct {
	EnvironmentID uuid.UUID `json:"environment_id"`
	AccountRef    string    `json:"account_ref"`
	ExternalID    string    `json:"external_id"`
	TrustAnchor   string    `json:"trust_anchor"`
}

func (q *Queries) CreateEnvironmentAWSConfig(ctx context.Context, arg CreateEnvironmentAWSConfigParams) (EnvironmentAwsConfig, error) {
	row := q.db.QueryRowContext(ctx, createEnvironmentAWSConfig,
		arg.EnvironmentID,
		arg.AccountRef,
		arg.ExternalID,
		arg.TrustAnchor,
	)
	var i EnvironmentAwsConfig
	err := row.Scan(
		&i.EnvironmentID,
		&i.AccountRef,
		&i.ExternalID,
		&i.TrustAnchor,
	)
	return i, err
}

const createEnvironmentAWSTierRole = `-- name: CreateEnvironmentAWSTierRole :one
INSERT INTO environment_aws_tier_roles (environment_id, tier, role_arn) VALUES ($1, $2, $3) RETURNING environment_id, tier, role_arn
`

type CreateEnvironmentAWSTierRoleParams struct {
	EnvironmentID uuid.UUID `json:"environment_id"`
	Tier          int16     `json:"tier"`
	RoleArn       string    `json:"role_arn"`
}

func (q *Queries) CreateEnvironmentAWSTierRole(ctx context.Context, arg CreateEnvironmentAWSTierRoleParams) (EnvironmentAwsTierRole, error) {
	row := q.db.QueryRowContext(ctx, createEnvironmentAWSTierRole, arg.EnvironmentID, arg.Tier, arg.RoleArn)
	var i EnvironmentAwsTierRole
	err := row.Scan(&i.EnvironmentID, &i.Tier, &i.RoleArn)
	return i, err
}

const getEnvironment = `-- name: GetEnvironment :one
SELECT id, tenant_id, name, provider, region, created_at FROM environments WHERE id = $1
`

func (q *Queries) GetEnvironment(ctx context.Context, id uuid.UUID) (Environment, error) {
	row := q.db.QueryRowContext(ctx, getEnvironment, id)
	var i Environment
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.Provider,
		&i.Region,
		&i.CreatedAt,
	)
	return i, err
}

const getEnvironmentAWSConfig = `-- name: GetEnvironmentAWSConfig :one
SELECT environment_id, account_ref, external_id, trust_anchor FROM environment_aws_config WHERE environment_id = $1
`

func (q *Queries) GetEnvironmentAWSConfig(ctx context.Context, environmentID uuid.UUID) (EnvironmentAwsConfig, error) {
	row := q.db.QueryRowContext(ctx, getEnvironmentAWSConfig, environmentID)
	var i EnvironmentAwsConfig
	err := row.Scan(
		&i.EnvironmentID,
		&i.AccountRef,
		&i.ExternalID,
		&i.TrustAnchor,
	)
	return i, err
}

const getEnvironmentAWSTierRole = `-- name: GetEnvironmentAWSTierRole :one
SELECT environment_id, tier, role_arn FROM environment_aws_tier_roles WHERE environment_id = $1 AND tier = $2
`

type GetEnvironmentAWSTierRoleParams struct {
	EnvironmentID uuid.UUID `json:"environment_id"`
	Tier          int16     `json:"tier"`
}

func (q *Queries) GetEnvironmentAWSTierRole(ctx context.Context, arg GetEnvironmentAWSTierRoleParams) (EnvironmentAwsTierRole, error) {
	row := q.db.QueryRowContext(ctx, getEnvironmentAWSTierRole, arg.EnvironmentID, arg.Tier)
	var i EnvironmentAwsTierRole
	err := row.Scan(&i.EnvironmentID, &i.Tier, &i.RoleArn)
	return i, err
}
