// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CreateEnvironment(ctx context.Context, arg CreateEnvironmentParams) (Environment, error)
	CreateEnvironmentAWSConfig(ctx context.Context, arg CreateEnvironmentAWSConfigParams) (EnvironmentAwsConfig, error)
	CreateEnvironmentAWSTierRole(ctx context.Context, arg CreateEnvironmentAWSTierRoleParams) (EnvironmentAwsTierRole, error)
	GetEnvironment(ctx context.Context, id uuid.UUID) (Environment, error)
	GetEnvironmentAWSConfig(ctx context.Context, environmentID uuid.UUID) (EnvironmentAwsConfig, error)
	GetEnvironmentAWSTierRole(ctx context.Context, arg GetEnvironmentAWSTierRoleParams) (EnvironmentAwsTierRole, error)
}

var _ Querier = (*Queries)(nil)
