// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	AnyTenantExists(ctx context.Context) (bool, error)
	CreateTenant(ctx context.Context, name string) (Tenant, error)
	GetTenant(ctx context.Context, id uuid.UUID) (Tenant, error)
}

var _ Querier = (*Queries)(nil)
