// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tenant.sql

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
)

const anyTenantExists = `-- name: AnyTenantExists :one
SELECT EXISTS (SELECT 1 FROM tenants) AS exists
`

func (q *Queries) AnyTenantExists(ctx context.Context) (bool, error) {
	row := q.db.QueryRowContext(ctx, anyTenantExists)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const createTenant = `-- name: CreateTenant :one
INSERT INTO tenants (name) VALUES ($1) RETURNING id, name, created_at
`

func (q *Queries) CreateTenant(ctx context.Context, name string) (Tenant, error) {
	row := q.db.QueryRowContext(ctx, createTenant, name)
	var i Tenant
	err := row.Scan(&i.ID, &i.Name, &i.CreatedAt)
	return i, err
}

const getSoleTenant = `-- name: GetSoleTenant :one
SELECT id, name, created_at FROM tenants LIMIT 1
`

func (q *Queries) GetSoleTenant(ctx context.Context) (Tenant, error) {
	row := q.db.QueryRowContext(ctx, getSoleTenant)
	var i Tenant
	err := row.Scan(&i.ID, &i.Name, &i.CreatedAt)
	return i, err
}

const getTenant = `-- name: GetTenant :one
SELECT id, name, created_at FROM tenants WHERE id = $1
`

func (q *Queries) GetTenant(ctx context.Context, id uuid.UUID) (Tenant, error) {
	row := q.db.QueryRowContext(ctx, getTenant, id)
	var i Tenant
	err := row.Scan(&i.ID, &i.Name, &i.CreatedAt)
	return i, err
}
