// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CreateTeam(ctx context.Context, arg CreateTeamParams) (Team, error)
	GetTeam(ctx context.Context, id uuid.UUID) (Team, error)
	GetTeamByName(ctx context.Context, arg GetTeamByNameParams) (Team, error)
}

var _ Querier = (*Queries)(nil)
