// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: audit.sql

package sqlcgen

import (
	"context"
	"database/sql"
	"encoding/json"

	"github.com/google/uuid"
)

const createAuditEvent = `-- name: CreateAuditEvent :one
INSERT INTO audit_events (tenant_id, actor_id, action, run_id, tier, environment_id, ttl_seconds, metadata)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8) RETURNING id, tenant_id, occurred_at, actor_id, action, run_id, tier, environment_id, ttl_seconds, metadata
`

type CreateAuditEventParams struct {
	TenantID      uuid.UUID       `json:"tenant_id"`
	ActorID       uuid.UUID       `json:"actor_id"`
	Action        string          `json:"action"`
	RunID         uuid.NullUUID   `json:"run_id"`
	Tier          sql.NullInt16   `json:"tier"`
	EnvironmentID uuid.NullUUID   `json:"environment_id"`
	TtlSeconds    sql.NullInt32   `json:"ttl_seconds"`
	Metadata      json.RawMessage `json:"metadata"`
}

func (q *Queries) CreateAuditEvent(ctx context.Context, arg CreateAuditEventParams) (AuditEvent, error) {
	row := q.db.QueryRowContext(ctx, createAuditEvent,
		arg.TenantID,
		arg.ActorID,
		arg.Action,
		arg.RunID,
		arg.Tier,
		arg.EnvironmentID,
		arg.TtlSeconds,
		arg.Metadata,
	)
	var i AuditEvent
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.OccurredAt,
		&i.ActorID,
		&i.Action,
		&i.RunID,
		&i.Tier,
		&i.EnvironmentID,
		&i.TtlSeconds,
		&i.Metadata,
	)
	return i, err
}

const getAuditEvent = `-- name: GetAuditEvent :one
SELECT id, tenant_id, occurred_at, actor_id, action, run_id, tier, environment_id, ttl_seconds, metadata FROM audit_events WHERE id = $1
`

func (q *Queries) GetAuditEvent(ctx context.Context, id uuid.UUID) (AuditEvent, error) {
	row := q.db.QueryRowContext(ctx, getAuditEvent, id)
	var i AuditEvent
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.OccurredAt,
		&i.ActorID,
		&i.Action,
		&i.RunID,
		&i.Tier,
		&i.EnvironmentID,
		&i.TtlSeconds,
		&i.Metadata,
	)
	return i, err
}
