// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CreateAuditEvent(ctx context.Context, arg CreateAuditEventParams) (AuditEvent, error)
	GetAuditEvent(ctx context.Context, id uuid.UUID) (AuditEvent, error)
}

var _ Querier = (*Queries)(nil)
